apiVersion: v1
kind: Secret
metadata:
    name: postgres-secret
type: Opaque
data:
    postgres-user: cG9zdGdyZXM=
    postgres-password: cG9zdGdyZXM=
    pgadmin_email: c2VtZW5rb3ZhLm9rc2FuYS53b3JrQGdtYWlsLmNvbQ==
    pgadmin-password: cG9zdGdyZXM=